# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f00ef9536069b0596feffce53fa5cf7b24d016fa5097f01cff426339e2b1b37a4449d845fade93c717f8b2e87cdd771869df57975cb0d63ef38a55685799719

test:
  secret_key_base: e9ee31c5196d7ad99526f844b1612898541bf5a61a4b77e7265b1d12eb2a218b5a7a0403c4c010d1df373f6b3c55bb9338b0bfc7eb0c0fcdfca6d00b29f49fe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
